option(IRONFAMILY_STRICT_WARNINGS "Enable strict warnings for first-party targets" OFF)
option(IRONFAMILY_ENABLE_SANITIZERS "Enable sanitizer instrumentation for supported compilers" OFF)

function(ironfamily_apply_dev_options target_name)
    if(NOT TARGET "${target_name}")
        message(FATAL_ERROR "ironfamily_apply_dev_options: unknown target '${target_name}'")
    endif()

    get_target_property(target_type "${target_name}" TYPE)
    if(target_type STREQUAL "INTERFACE_LIBRARY")
        return()
    endif()

    if(IRONFAMILY_STRICT_WARNINGS)
        if(MSVC)
            target_compile_options("${target_name}" PRIVATE /W4 /WX)
        elseif(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options("${target_name}" PRIVATE -Wall -Wextra -Wpedantic -Werror)
        endif()
    endif()

    if(IRONFAMILY_ENABLE_SANITIZERS)
        if(MSVC)
            target_compile_options("${target_name}" PRIVATE /fsanitize=address /Zi)
            target_link_options("${target_name}" PRIVATE /DEBUG /INFERASANLIBS)
        elseif(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options("${target_name}" PRIVATE -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer)
            target_link_options("${target_name}" PRIVATE -fsanitize=address -fsanitize=undefined)
        else()
            message(STATUS "Sanitizers requested for ${target_name}, but compiler support is unknown; leaving target unchanged.")
        endif()
    endif()
endfunction()
